version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.37

  fhir-pseudonymizer:
    image: harbor.miracum.org/miracum-etl/fhir-pseudonymizer:v2.12.0
    environment:
      JAEGER__HOST: jaeger
      JAEGER__PORT: 6831
      GPAS__URL: ${GPAS_URL:-http://gpas:8080/gpas/gpasService}
      GPAS__VERSION: ${GPAS_VERSION:-1.11.0}
    volumes:
      - ./anonymization.yaml:/etc/anonymization.yaml:ro
    depends_on:
      - jaeger
      - gpas

  loinc-converter:
    image: harbor.miracum.org/miracum-etl/loinc-conversion:v1.13.3
    environment:
      JAEGER_AGENT_HOST: jaeger
    depends_on:
      - jaeger

  fhir-db:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  mysql:
    image: mysql/mysql-server:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./wildfly/sqls:/docker-entrypoint-initdb.d
      #- ./wildfly/db_data:/var/lib/mysql

  gpas:
    image: mosaicgreifswald/wildfly:24.0.1.Final-20210917
    ports:
      - "8088:8080"
      - "9990:9990"
    environment:
      CONSOLE_LOG_LEVEL: DEBUG
      GPAS_FILE_LOG: "true"
      GPAS_LOG_LEVEL: DEBUG
      WILDFLY_PASS: wildfly_password
      JAVA_OPTS: "-server -Xms512m -Xmx1G -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman"
    depends_on:
      - mysql
    volumes:
      - ./wildfly/jboss:/entrypoint-wildfly-cli
      - ./wildfly/deployments:/entrypoint-wildfly-deployments
      - ./wildfly/logs:/entrypoint-wildfly-logs
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 120 && ./run.sh"

  fhir-server:
    image: docker.io/hapiproject/hapi:v5.6.0-distroless

  gpasinit-patient:
    image: curlimages/curl:7.84.0
    command: |
      -X POST
      -H 'Content-Type:application/xml'
      -d '<?xml version="1.0" encoding="UTF-8"?>
          <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:psn="http://psn.ttp.ganimed.icmvc.emau.org/">
            <soapenv:Header/>
              <soapenv:Body>
                <psn:addDomain>
                  <domainDTO>
                    <name>PATIENT</name>
                    <checkDigitClass>org.emau.icmvc.ganimed.ttp.psn.generator.ReedSolomonLagrange</checkDigitClass>
                    <alphabet>org.emau.icmvc.ganimed.ttp.psn.alphabets.Symbol31</alphabet>
                    <properties>PSN_LENGTH=31;PSN_PREFIX=p;INCLUDE_PREFIX_IN_CHECK_DIGIT_CALCULATION=false;PSNS_DELETABLE=true;MAX_DETECTED_ERRORS=2;</properties>
                    <comment>PATIENT Domain</comment>
                  </domainDTO>
                </psn:addDomain>
            </soapenv:Body>
          </soapenv:Envelope>'
      --retry-connrefuse
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      http://gpas:8080/gpas/DomainService
    depends_on:
      - gpas

  gpasinit-fall:
    image: curlimages/curl:7.84.0
    command: |
      -X POST
      -H 'Content-Type:application/xml'
      -d '<?xml version="1.0" encoding="UTF-8"?>
          <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:psn="http://psn.ttp.ganimed.icmvc.emau.org/">
            <soapenv:Header/>
              <soapenv:Body>
                <psn:addDomain>
                  <domainDTO>
                    <name>FALL</name>
                    <checkDigitClass>org.emau.icmvc.ganimed.ttp.psn.generator.ReedSolomonLagrange</checkDigitClass>
                    <alphabet>org.emau.icmvc.ganimed.ttp.psn.alphabets.Symbol31</alphabet>
                    <properties>PSN_LENGTH=31;PSN_PREFIX=f;INCLUDE_PREFIX_IN_CHECK_DIGIT_CALCULATION=false;PSNS_DELETABLE=true;MAX_DETECTED_ERRORS=2;</properties>
                    <comment>FALL Domain</comment>
                  </domainDTO>
                </psn:addDomain>
            </soapenv:Body>
          </soapenv:Envelope>'
      --retry-connrefuse
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      http://gpas:8080/gpas/DomainService
    depends_on:
      - gpas
